from typing import TypedDict, Annotated
from langgraph.types import interrupt, Command
from langgraph.graph.message import add_messages
from langgraph.graph import StateGraph, START, END
from langgraph.checkpoint.memory import MemorySaver

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage

import os
import smtplib

from email.message import EmailMessage

from dotenv import load_dotenv

load_dotenv()

EMAIL = os.getenv("EMAIL")
PASSWORD = os.getenv("APP_PASSWORD")      # Gmail App Password
RECEIVER = os.getenv("RECEIVER")


class GraphState(TypedDict):
    messages: Annotated[list, add_messages]
    email: str
    approved: bool
    feedback: str          # texte libre saisi par l'humain



llm = ChatOpenAI(
    base_url="http://localhost:11434/v1",
    api_key="ollama",
    model="qwen2.5:14b",
    temperature=0,
)

def write_email(state: GraphState):

    prompt = HumanMessage(
        content="""
        Write a professional vacation request email.
        The employee wants 5 days of vacation.
        Only return the email body.
        """
    )

    response = llm.invoke([prompt])

    print("\n========== GENERATED EMAIL ==========\n")
    print(response.content)

    return {
        "messages": [response],
        "email": response.content,
    }


def human_review(state: GraphState):

    print("\n========== HUMAN REVIEW ==========\n")
    print(state["email"])

    # L'humain répond en texte libre (approbation OU instructions de modification)
    feedback = interrupt(
        {
            "question": "Your feedback? (approve, or describe what to change)",
            "email": state["email"]
        }
    )

    return {
        "feedback": feedback
    }


def classify_decision(state: GraphState):

    print("\n========== CLASSIFYING HUMAN DECISION ==========\n")

    prompt = HumanMessage(
        content=f"""
    A human reviewed an email and gave the following feedback.

    Decide if the human APPROVED the email as-is, or wants CHANGES.

    Reply with exactly one word:
    - "APPROVED" if they accept it and want it sent.
    - "CHANGES" if they want any modification.

    Human feedback:
    {state["feedback"]}
    """
    )

    response = llm.invoke([prompt])
    decision = response.content.strip().upper()

    approved = "APPROVED" in decision
    print(f"LLM decision: {decision} -> approved={approved}")

    return {
        "approved": approved
    }


def send_email(state: GraphState):

    print("\n========== SENDING EMAIL ==========\n")

    msg = EmailMessage()

    msg["Subject"] = "Vacation Request"
    msg["From"] = EMAIL
    msg["To"] = RECEIVER

    # Email generated by the LLM
    msg.set_content(state["email"])

    with smtplib.SMTP("smtp.gmail.com", 587) as smtp:
        smtp.starttls()
        smtp.login(EMAIL, PASSWORD)
        smtp.send_message(msg)

    print("✅ Email sent successfully!")

    return {}


def rewrite_email(state: GraphState):

    print("\n========== REWRITING EMAIL ==========\n")

    prompt = HumanMessage(
        content=f"""
    The following email was reviewed by a human who requested changes.

    Rewrite the email by applying the human's instructions.
    Keep it professional, polite, and persuasive.

    Human instructions:
    {state["feedback"]}

    Current email:
    {state["email"]}

    Only return the new email.
    """
    )

    response = llm.invoke([prompt])

    print(response.content)

    return {
        "messages": [response],
        "email": response.content,
    }


# ---------- ROUTING ----------
def route_after_review(state: GraphState):
    return "send_email" if state["approved"] else "rewrite_email"


# ---------- GRAPH ----------
builder = StateGraph(GraphState)

# Nodes
builder.add_node("write_email", write_email)
builder.add_node("human_review", human_review)
builder.add_node("classify_decision", classify_decision)
builder.add_node("send_email", send_email)
builder.add_node("rewrite_email", rewrite_email)

# Edges
builder.add_edge(START, "write_email")
builder.add_edge("write_email", "human_review")
builder.add_edge("human_review", "classify_decision")

builder.add_conditional_edges(
    "classify_decision",
    route_after_review,
    {
        "send_email": "send_email",
        "rewrite_email": "rewrite_email",
    },
)

builder.add_edge("rewrite_email", "human_review")
builder.add_edge("send_email", END)

# Checkpointer requis pour interrupt()
checkpointer = MemorySaver()
graph = builder.compile(checkpointer=checkpointer)


# ---------- EXECUTION ----------
if __name__ == "__main__":
    config = {"configurable": {"thread_id": "1"}}

    # 1er run : s'arrête sur l'interrupt (human_review)
    result = graph.invoke({"messages": []}, config=config)

    # Boucle human-in-the-loop
    while True:
        state = graph.get_state(config)

        # Plus d'interrupt => le graphe est terminé
        if not state.interrupts:
            break

        # Affiche la question de l'interrupt
        interrupt_data = state.interrupts[0].value
        print("\n========== VOTRE FEEDBACK ==========\n")
        print(interrupt_data["question"])

        # Texte libre : approbation ou instructions de modification
        feedback = input("> ").strip()

        # Reprend avec le texte de l'humain (le LLM décidera ensuite)
        result = graph.invoke(Command(resume=feedback), config=config)

    print("\n========== TERMINÉ ==========")